services:
  - type: web
    name: movanta
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: COOKIE_SECURE
        value: "true"
      - key: FLASK_ENV
        value: production
      - key: PYTHON_ENV
        value: production
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DB_POOL_RECYCLE_SECONDS
        value: "300"
      - key: JWT_SECRET
        sync: false
